(async()=>{
  const base=app.vault.adapter.getBasePath();if(base!=='D:\\Workspaces\\OpenContent\\validation-vault')throw Error('Wrong Vault');
  const plugin=app.plugins.plugins.opencontent;const fs=require('fs');
  const connection=JSON.parse(fs.readFileSync('D:/Workspaces/OpenContent/.validation-runtime/wechat-fixture.json','utf8'));
  plugin.connection=connection;await plugin.open('publishing');
  const view=app.workspace.getLeavesOfType('opencontent-cockpit')[0].view;view.selected=connection.project;
  const checks=[];const check=(name,ok)=>{checks.push({name,pass:!!ok});if(!ok)throw Error(name);};
  const wait=async test=>{for(let i=0;i<50;i++){if(await test())return;await new Promise(r=>setTimeout(r,100));}throw Error('UI timeout');};
  const click=(scope,label)=>{const button=[...scope.querySelectorAll('button')].find(b=>b.textContent===label);if(!button)throw Error('Missing '+label);button.click();};
  const modal=()=>document.querySelector('.oc-modal');
  const fill=(label,value)=>{const input=modal().querySelector(`[aria-label="${label}"]`);if(!input)throw Error('Missing field '+label);input.value=value;};
  check('new_navigation_visible',document.querySelector('.oc-root').textContent.includes('材料库')&&document.querySelector('.oc-root').textContent.includes('发布与反馈'));
  await plugin.open('sources');check('source_library_reads_captured_note',document.querySelector('.oc-root').textContent.includes('v0.4-来源验收.md'));
  await plugin.open('project');view.selected=connection.project;await view.render();
  document.querySelector('.oc-root [aria-label="计划发表日期"]').value='2026-09-22';
  click(document.querySelector('.oc-root'),'保存计划');
  await wait(async()=> (await plugin.api('/objects/'+connection.project)).object.planning?.planned_for==='2026-09-22');
  check('project_plan_saved',true);
  await wait(()=>!view.rendering);
  await view.prepareDraft((await plugin.api('/objects/'+connection.artifact)).object);await wait(()=>modal());
  fill('公众号标题（32 字）','v0.4 微信界面验收');fill('作者（16 字）','软件验收');fill('摘要（120 字）','模拟微信协议，不代表实际公众号发表。');fill('封面 thumb_media_id','fixture-cover');
  click(modal(),'生成投递预览');await wait(()=>modal()?.querySelector('iframe'));
  check('preview_is_sandboxed',modal().querySelector('iframe').getAttribute('sandbox')==='');
  check('preview_shows_account_and_digest',modal().textContent.includes('wx0123456789abcdef')&&modal().textContent.includes('模拟微信协议'));
  click(modal(),'确认送入草稿箱');await wait(()=>[...document.querySelectorAll('.notice')].some(n=>n.textContent.includes('勾选')));
  check('unchecked_confirmation_does_not_send',(await plugin.api('/publications')).publications.find(p=>p.artifact===connection.artifact).delivery_status==='PREPARED');
  fill('本次投递确认人','软件界面验收人');modal().querySelector('input[type="checkbox"]').checked=true;
  click(modal(),'确认送入草稿箱');await wait(()=>!modal());await wait(()=>!view.rendering);
  let pubs=(await plugin.api('/publications')).publications.filter(p=>p.artifact===connection.artifact);
  check('draft_round_trip_confirmed',pubs.some(p=>p.delivery_status==='REMOTE_DRAFT'));
  const draft=pubs.find(p=>p.delivery_status==='REMOTE_DRAFT');
  const card=()=>[...document.querySelectorAll('.oc-card')].find(c=>c.textContent.includes('v0.4 微信界面验收')&&c.textContent.includes('微信草稿已核验'));
  click(card(),'核对草稿并准备发表');await wait(()=>modal()?.textContent.includes('确认向公众发表'));
  check('publish_requires_separate_confirmation',modal().textContent.includes('不是群发操作'));
  fill('本次投递确认人','软件界面验收人');modal().querySelector('input[type="checkbox"]').checked=true;
  click(modal(),'确认发表');await wait(()=>!modal());await wait(()=>!view.rendering);
  pubs=(await plugin.api('/publications')).publications.filter(p=>p.artifact===connection.artifact);
  const published=pubs.find(p=>p.delivery_status==='PUBLISHED');check('verified_receipt_visible',!!published&&document.querySelector('.oc-root').textContent.includes('已发表并核验'));
  const publishedCard=()=>[...document.querySelectorAll('.oc-card')].find(c=>c.textContent.includes('v0.4 微信界面验收')&&c.textContent.includes('已发表并核验'));
  click(publishedCard(),'记录读者反馈 / 数据观察');await wait(()=>modal());
  fill('反馈来源 / 数据日期','合成读者反馈 2026-09-08');fill('观察到的事实','验收读者希望增加操作步骤');fill('建议下次如何改进','下一篇增加逐步截图教程');
  click(modal(),'保存待判断反馈');await wait(()=>!modal());await wait(()=>!view.rendering);
  click(publishedCard(),'判断这条经验');await wait(()=>modal());fill('经验判断人','软件界面验收人');fill('接受或拒绝的依据','合成反馈说明示例不足，需要逐步补充。');
  click(modal(),'接受经验');await wait(()=>!modal());await wait(()=>!view.rendering);
  check('human_lesson_decision_visible',publishedCard().textContent.includes('判断：accept'));
  click(publishedCard(),'带入下一个项目');await wait(()=>modal());fill('项目名称','v0.4 反馈复用软件验收');fill('项目目标','验证已接受经验进入下一项目');fill('目标读者','软件验收人员');
  click(modal(),'创建并打开');await wait(()=>!modal());await wait(()=>!view.rendering);
  const next=(await plugin.api('/board')).projects.find(p=>p.title==='v0.4 反馈复用软件验收');
  check('feedback_seeds_next_project',next?.editorial_lessons?.[0].lesson==='下一篇增加逐步截图教程');
  await plugin.open('publishing');
  const result={at:new Date().toISOString(),plugin:plugin.manifest.version,scope:'Real Obsidian UI and real local HTTP/Markdown; injected WeChat protocol fixture, NO real publication',checks,project:connection.project,publication:published.oc_id,next_project:next.oc_id};
  fs.writeFileSync('D:/Workspaces/OpenContent/docs/obsidian-lifecycle-v0.4.json',JSON.stringify(result,null,2));return result;
})()
